# Sample Configuration file
# This config is divided into 3 environments, namely *, development and production
# *: holds configuration parameters that are the same in both development and production,
#    so you don't have to declare these twice
# development: holds configuration parameters that are applicable to only the development environment
# production: configuration parameters that are applicable to only the production environment

*:
  database:
    type: mysql
  memcached:
    port: 11211
  mailer:
    use: mandrill
    # default from_address
    from:
      name: PICC Nigeria
      email: info@picc.com.ng
    # default to_address
    to:
      name: PICC Nigeria
      email: info@picc.com.ng
  # Set directories to upload files
  uploads:
    cases: uploads/cases/ # Ensure to include the trailing /

development:
  database:
    name: picc_db
    host: localhost
    user: root
    password:
  memcached:
    host: localhost
  mailer:
    api_key: MANDRILL_API_KEY # Enter a valid API KEY here
    # Comment out the next line if you wish to send emails in development env
    pretend: true

production:
  database:
    name: DATABASE_NAME
    host: DATABASE_HOST
    user: DATABASE_USER
    password: DATABASE_PASSWORD
  memcached:
    host: MEMCACHED_HOST
  mailer:
    api_key: MANDRILL_API_KEY # Enter a valid API KEY here